version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  python: circleci/python@1.2
  node: circleci/node@2.0.2 


# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.9.7
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest tests/dummy.py
      - run: echo echo ${MY_ENV_VAR_NAME}
  print_hello:
    docker: 
      - image: cimg/node:16.12.0
    steps:
      - checkout
      - run:
          name: Print hello
          command: node node_echo.js hello
  print_world:
    docker: 
      - image: cimg/node:16.12.0
    steps:
      - checkout
      - run:
          name: Print hello
          command: node node_echo.js world      
      - run: echo "Pipeline.ID = << pipeline.id >> branch = << pipeline.git.branch >>"
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample-workflow-for-nodejs:
    jobs: 
      - print_hello
      - print_world:
          requires: 
            - print_hello
  sample-workflow-for-python: 
    jobs:
      - build-and-test
